[telescope]
TelescopeDiameter = 1.82
ZenithAngle = 0.0
ObscurationRatio = 0.33
PathPupil = '/raid1/mmenessini/git/P3/p3/aoSystem/data/EKARUS_CALIBRATION/copernico_pupil_160pixels.fits'
Resolution = 160
TechnicalFoV = 30

[atmosphere]
Wavelength = 500e-9
Seeing = 1.8
L0 = 25.0
Cn2Weights = [0.70, 0.06, 0.14, 0.10]
Cn2Heights = [119.,  837., 3045., 12780.]
WindSpeed = [5., 10., 30., 20.]
WindDirection = [222., 70., 145., 0.]

[sources_science]
Wavelength = [750e-9]
Zenith = [0.0]
Azimuth = [0.0]

[sources_HO]
Wavelength = [750e-9]
Zenith = [0.0]
Azimuth = [0.0]
Height = 0.0

; [sources_LO]
; Wavelength = [750e-9]
; Zenith = [0.0]
; Azimuth = [0.0]
; Height = 0.0

[sensor_science]
PixelScale = 15  # [mas]
FieldOfView = 400

[sensor_HO]
WfsType = 'Pyramid'
Modulation = 4
Binning = 1 
PixelScale = 714      # [mas]
FieldOfView = 2  
NumberPhotons = [10]    # [nph/frame/subaperture]
SigmaRON = 0.4           # [e-]     
; Dark = 1.0
; SkyBackground = 50.0
; Gain = 1.0    
ExcessNoiseFactor = 2.0 
NumberLenslets = [42]    
; SizeLenslets = [0.043] 
noNoise = False

[DM]
NumberActuators = [24]
DmPitchs = [0.0758]
DmHeights = [0.0] 
AoArea = 'square'
InfModel = 'gaussian' # IF model
InfCoupling = [0.275]   # IF coupling

[RTC]
LoopGain_HO = 0.7 #'optimize'                           
SensorFrameRate_HO = 1000
LoopDelaySteps_HO = 2  
; LoopGain_LO = 'optimize'                           
; SensorFrameRate_LO = 2000
; LoopDelaySteps_LO = 1.5  
