[telescope]
TelescopeDiameter = 8.2
ZenithAngle = 0.0
ObscurationRatio = 0.14
Resolution = 160
TechnicalFoV = 30

[atmosphere]
Wavelength = 500e-9
Seeing = 0.88
L0 = 25.0
Cn2Weights = [0.70, 0.06, 0.14, 0.10]
Cn2Heights = [119.,  837., 3045., 12780.]
WindSpeed = [5., 10., 30., 20.]
WindDirection = [222., 70., 145., 0.]

[sources_science]
Wavelength = [840e-9]
Zenith = [0.0]
Azimuth = [0.0]

[sources_HO]
Wavelength = [925e-9]
Zenith = [0.0]
Azimuth = [0.0]
Height = 0.0


[sensor_science]
PixelScale = 3         # [mas/pix]
FieldOfView = -1

[sensor_HO]
WfsType = 'Pyramid'
Modulation = 2
Binning = 1 
PixelScale = 200      # [mas]
FieldOfView = 2  
NumberPhotons = [1000]    # [nph/frame/subaperture]
SigmaRON = 0.5           # [e-]     
; Dark = 1.0
; SkyBackground = 50.0
; Gain = 1.0    
ExcessNoiseFactor = 2.0 
NumberLenslets = [48]    
; SizeLenslets = [0.043] 
noNoise = False


[DM]
NumberActuators = [40]
DmPitchs = [0.205]
DmHeights = [0.0] 
AoArea = 'square'
InfModel = 'gaussian' # IF model
InfCoupling = [0.1]   # IF coupling


[RTC]
LoopGain_HO = 0.5                               
SensorFrameRate_HO = 2000.0
LoopDelaySteps_HO = 1.5  
