[telescope]
TelescopeDiameter = 8.22
ZenithAngle = 0.0
ObscurationRatio = 0.111
Resolution = 160
TechnicalFoV = 30

[atmosphere]
Wavelength = 500e-9
Seeing = 0.8
L0 = 40.0
Cn2Weights = [0.70, 0.06, 0.14, 0.10]
Cn2Heights = [119.,  837., 3045., 12780.]
WindSpeed = [5., 10., 30., 20.]
WindDirection = [222., 70., 145., 0.]

[sources_science]
Wavelength = [2150e-9]
Zenith = [0.0]
Azimuth = [0.0]

[sources_HO]
Wavelength = [750e-9]
Zenith = [0.0]
Azimuth = [0.0]
Height = 0.0


[sensor_science]
PixelScale = 14.9
FieldOfView = 256

[sensor_HO]
WfsType = 'Pyramid'
Modulation = 3
Binning = 1 
PixelScale = 714      # [mas]
FieldOfView = 2  
NumberPhotons = [100]    # [nph/frame/subaperture]
SigmaRON = 0.4           # [e-]     
; Dark = 1.0
; SkyBackground = 50.0
; Gain = 1.0    
ExcessNoiseFactor = 2.0 
NumberLenslets = [40]    
; SizeLenslets = [0.043] 
noNoise = False


[DM]
NumberActuators = [30]
DmPitchs = [0.275]
DmHeights = [0.0] 
AoArea = 'circle'
; InfModel = 'gaussian' # IF model


[RTC]
LoopGain_HO = 0.5                               
SensorFrameRate_HO = 1500.0
LoopDelaySteps_HO = 3   
